@baseUrl = http://localhost:3333

# @name create
POST {{baseUrl}}/session
Content-Type: application/json

{
  "email": "jose@gmail.com",
  "password": "123123"
}

###

# @name refresh
POST {{baseUrl}}/session/refresh
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ7XCJhY2NvdW50SWRcIjpcIjkxOTBmNTZkLTU1NDgtNDIzYy1hNWRmLWJjZjkwMzRiNTQ5OFwifSIsImlhdCI6MTczNTc3OTExMiwiZXhwIjoxNzM1ODY1NTEyfQ.NOD8fsroOj9IbZydeaw_a4_70HQo0tQQkv5jLgRU7Ow"
}